[build]
builder = "nixpacks"
buildCommand = "cd shared && npm install && npm run build && cd ../frontend && npm install && npm run build"
watchPatterns = ["frontend/**/*", "shared/**/*"]

[deploy]
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 